catalogMode: prefer
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade
trustPolicyExclude:
  - cached-factory@0.1.0

packages:
  - fixtures/*

catalogs:
  dev:
    '@antfu/ni': ^28.2.0
    '@eslint/config-inspector': ^1.4.2
    '@types/eslint-plugin-jsx-a11y': ^6.10.1
    '@types/node': ^25.0.9
    bumpp: ^10.4.0
    chokidar: ^5.0.0
    eslint-typegen: ^2.3.0
    execa: ^9.6.1
    jiti: ^2.6.1
    lint-staged: ^16.2.7
    pnpm-workspace-yaml: ^1.5.0
    semver: ^7.7.3
    simple-git-hooks: ^2.13.1
    synckit: ^0.11.12
    tinyglobby: ^0.2.15
    tsdown: ^0.18.4
    tsx: ^4.21.0
    typescript: ^5.9.3
    vitest: ^4.0.17
  inline:
    find-up-simple: ^1.0.1
  peer:
    '@eslint-community/eslint-utils': ^4.9.1
    '@eslint-react/eslint-plugin': ^2.7.2
    '@next/eslint-plugin-next': ^16.1.4
    '@prettier/plugin-xml': ^3.4.2
    '@typescript-eslint/types': ^8.53.1
    '@typescript-eslint/utils': ^8.53.1
    '@unocss/eslint-plugin': ^66.6.0
    astro-eslint-parser: ^1.2.2
    eslint: ^9.39.2
    eslint-plugin-astro: ^1.5.0
    eslint-plugin-erasable-syntax-only: ^0.4.0
    eslint-plugin-format: ^1.3.1
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
    eslint-plugin-solid: ^0.14.5
    eslint-plugin-svelte: ^3.14.0
    eslint-plugin-vuejs-accessibility: ^2.4.1
    prettier-plugin-astro: ^0.14.1
    prettier-plugin-slidev: ^1.0.5
    svelte: ^5.47.1
    svelte-eslint-parser: ^1.4.1
    vue: ^3.5.27
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.6.0
    '@eslint/markdown': ^7.5.1
    '@stylistic/eslint-plugin': ^5.7.0
    '@typescript-eslint/eslint-plugin': ^8.53.1
    '@typescript-eslint/parser': ^8.53.1
    '@vitest/eslint-plugin': ^1.6.6
    ansis: ^4.2.0
    cac: ^6.7.14
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^3.0.0
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.3
    eslint-plugin-command: ^3.4.0
    eslint-plugin-import-lite: ^0.5.0
    eslint-plugin-jsdoc: ^62.3.0
    eslint-plugin-jsonc: ^2.21.0
    eslint-plugin-n: ^17.23.2
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^5.3.1
    eslint-plugin-pnpm: ^1.5.0
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-toml: ^1.0.3
    eslint-plugin-unicorn: ^62.0.0
    eslint-plugin-unused-imports: ^4.3.0
    eslint-plugin-vue: ^10.7.0
    eslint-plugin-yml: ^3.0.0
    eslint-processor-vue-blocks: ^2.0.0
    globals: ^17.0.0
    jsonc-eslint-parser: ^2.4.2
    local-pkg: ^1.1.2
    parse-gitignore: ^2.0.0
    toml-eslint-parser: ^1.0.3
    vue-eslint-parser: ^10.2.0
    yaml-eslint-parser: ^2.0.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
