packages:
  - fixtures/*

strictPeerDependencies: false
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
shellEmulator: true

overrides:
  '@eslint-community/eslint-utils': ^4.9.0
  '@typescript-eslint/types': ^8.44.0
  '@typescript-eslint/utils': ^8.44.0
  eslint: ^9.36.0
  tsx: ^4.20.5
catalogs:
  dev:
    '@antfu/ni': ^26.0.1
    '@eslint/config-inspector': ^1.3.0
    '@types/eslint-plugin-jsx-a11y': ^6.10.0
    '@types/node': ^24.5.2
    bumpp: ^10.2.3
    eslint-typegen: ^2.3.0
    execa: ^9.6.0
    jiti: ^2.5.1
    lint-staged: ^16.1.6
    pnpm-workspace-yaml: ^1.1.1
    simple-git-hooks: ^2.13.1
    tinyglobby: ^0.2.15
    tsdown: ^0.14.2
    tsx: ^4.20.5
    typescript: ^5.9.2
    vitest: ^3.2.4
  peer:
    '@eslint-react/eslint-plugin': ^2.0.1
    '@next/eslint-plugin-next': ^15.5.3
    '@prettier/plugin-xml': ^3.4.2
    '@unocss/eslint-plugin': ^66.5.1
    astro-eslint-parser: ^1.2.2
    eslint: ^9.36.0
    eslint-plugin-astro: ^1.3.1
    eslint-plugin-format: ^1.0.1
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    eslint-plugin-solid: ^0.14.5
    eslint-plugin-svelte: ^3.12.3
    eslint-plugin-vuejs-accessibility: ^2.4.1
    prettier-plugin-astro: ^0.14.1
    prettier-plugin-slidev: ^1.0.5
    svelte: ^5.39.2
    svelte-eslint-parser: ^1.3.2
    vue: ^3.5.21
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint/markdown': ^7.2.0
    '@stylistic/eslint-plugin': ^5.4.0
    '@typescript-eslint/eslint-plugin': ^8.44.0
    '@typescript-eslint/parser': ^8.44.0
    '@vitest/eslint-plugin': ^1.3.12
    ansis: ^4.1.0
    cac: ^6.7.14
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.1.1
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.3.1
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-jsdoc: ^59.0.2
    eslint-plugin-jsonc: ^2.20.1
    eslint-plugin-n: ^17.23.1
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^4.15.0
    eslint-plugin-pnpm: ^1.1.1
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^61.0.2
    eslint-plugin-unused-imports: ^4.2.0
    eslint-plugin-vue: ^10.4.0
    eslint-plugin-yml: ^1.18.0
    eslint-processor-vue-blocks: ^2.0.0
    globals: ^16.4.0
    jsonc-eslint-parser: ^2.4.0
    local-pkg: ^1.1.2
    parse-gitignore: ^2.0.0
    toml-eslint-parser: ^0.10.0
    vue-eslint-parser: ^10.2.0
    yaml-eslint-parser: ^1.3.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
