catalogMode: prefer
cleanupUnusedCatalogs: true
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - fixtures/*

overrides:
  '@eslint-community/eslint-utils': ^4.9.0
  '@typescript-eslint/types': ^8.48.1
  '@typescript-eslint/utils': ^8.48.1
  eslint: ^9.39.1
  tsx: ^4.21.0

catalogs:
  dev:
    '@antfu/ni': ^28.0.0
    '@eslint/config-inspector': ^1.4.2
    '@types/eslint-plugin-jsx-a11y': ^6.10.1
    '@types/node': ^24.10.1
    bumpp: ^10.3.2
    eslint-typegen: ^2.3.0
    execa: ^9.6.1
    jiti: ^2.6.1
    lint-staged: ^16.2.7
    pnpm-workspace-yaml: ^1.4.1
    simple-git-hooks: ^2.13.1
    tinyglobby: ^0.2.15
    tsdown: ^0.15.12
    tsx: ^4.21.0
    typescript: ^5.9.3
    vitest: ^4.0.15
  inline:
    find-up-simple: ^1.0.1
  peer:
    '@eslint-react/eslint-plugin': ^2.3.12
    '@next/eslint-plugin-next': ^16.0.7
    '@prettier/plugin-xml': ^3.4.2
    '@unocss/eslint-plugin': ^66.5.10
    astro-eslint-parser: ^1.2.2
    eslint: ^9.39.1
    eslint-plugin-astro: ^1.5.0
    eslint-plugin-erasable-syntax-only: ^0.4.0
    eslint-plugin-format: ^1.0.2
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
    eslint-plugin-solid: ^0.14.5
    eslint-plugin-svelte: ^3.13.0
    eslint-plugin-vuejs-accessibility: ^2.4.1
    prettier-plugin-astro: ^0.14.1
    prettier-plugin-slidev: ^1.0.5
    svelte: ^5.45.5
    svelte-eslint-parser: ^1.4.1
    vue: ^3.5.25
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint/markdown': ^7.5.1
    '@stylistic/eslint-plugin': ^5.6.1
    '@typescript-eslint/eslint-plugin': ^8.48.1
    '@typescript-eslint/parser': ^8.48.1
    '@vitest/eslint-plugin': ^1.5.1
    ansis: ^4.2.0
    cac: ^6.7.14
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.1.4
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.3.1
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-jsdoc: ^61.4.1
    eslint-plugin-jsonc: ^2.21.0
    eslint-plugin-n: ^17.23.1
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^4.15.1
    eslint-plugin-pnpm: ^1.4.1
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^62.0.0
    eslint-plugin-unused-imports: ^4.3.0
    eslint-plugin-vue: ^10.6.2
    eslint-plugin-yml: ^1.19.0
    eslint-processor-vue-blocks: ^2.0.0
    globals: ^16.5.0
    jsonc-eslint-parser: ^2.4.1
    local-pkg: ^1.1.2
    parse-gitignore: ^2.0.0
    toml-eslint-parser: ^0.10.0
    vue-eslint-parser: ^10.2.0
    yaml-eslint-parser: ^1.3.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver

strictPeerDependencies: false
