packages:
  - fixtures/*

strictPeerDependencies: false
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
shellEmulator: true

overrides:
  '@eslint-community/eslint-utils': ^4.9.0
  '@typescript-eslint/types': ^8.46.1
  '@typescript-eslint/utils': ^8.46.1
  eslint: ^9.37.0
  tsx: ^4.20.6
catalogs:
  dev:
    '@antfu/ni': ^26.1.0
    '@eslint/config-inspector': ^1.3.0
    '@types/eslint-plugin-jsx-a11y': ^6.10.1
    '@types/node': ^24.7.2
    bumpp: ^10.3.1
    eslint-typegen: ^2.3.0
    execa: ^9.6.0
    jiti: ^2.6.1
    lint-staged: ^16.2.4
    pnpm-workspace-yaml: ^1.2.0
    simple-git-hooks: ^2.13.1
    tinyglobby: ^0.2.15
    tsdown: ^0.15.7
    tsx: ^4.20.6
    typescript: ^5.9.3
    vitest: ^3.2.4
  peer:
    '@eslint-react/eslint-plugin': ^2.2.2
    '@next/eslint-plugin-next': ^15.5.5
    '@prettier/plugin-xml': ^3.4.2
    '@unocss/eslint-plugin': ^66.5.3
    astro-eslint-parser: ^1.2.2
    eslint: ^9.37.0
    eslint-plugin-astro: ^1.3.1
    eslint-plugin-erasable-syntax-only: ^0.3.1
    eslint-plugin-format: ^1.0.2
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-react-hooks: ^7.0.0
    eslint-plugin-react-refresh: ^0.4.23
    eslint-plugin-solid: ^0.14.5
    eslint-plugin-svelte: ^3.12.4
    eslint-plugin-vuejs-accessibility: ^2.4.1
    prettier-plugin-astro: ^0.14.1
    prettier-plugin-slidev: ^1.0.5
    svelte: ^5.40.0
    svelte-eslint-parser: ^1.3.3
    vue: ^3.5.22
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint/markdown': ^7.4.0
    '@stylistic/eslint-plugin': ^5.4.0
    '@typescript-eslint/eslint-plugin': ^8.46.1
    '@typescript-eslint/parser': ^8.46.1
    '@vitest/eslint-plugin': ^1.3.20
    ansis: ^4.2.0
    cac: ^6.7.14
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.1.4
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.3.1
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-jsdoc: ^59.1.0
    eslint-plugin-jsonc: ^2.21.0
    eslint-plugin-n: ^17.23.1
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^4.15.1
    eslint-plugin-pnpm: ^1.2.0
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^61.0.2
    eslint-plugin-unused-imports: ^4.2.0
    eslint-plugin-vue: ^10.5.0
    eslint-plugin-yml: ^1.19.0
    eslint-processor-vue-blocks: ^2.0.0
    globals: ^16.4.0
    jsonc-eslint-parser: ^2.4.1
    local-pkg: ^1.1.2
    parse-gitignore: ^2.0.0
    toml-eslint-parser: ^0.10.0
    vue-eslint-parser: ^10.2.0
    yaml-eslint-parser: ^1.3.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
